# Generated by Django 5.1.4 on 2025-01-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RES_LNAME', models.CharField(max_length=50)),
                ('RES_FNAME', models.CharField(max_length=50)),
                ('RES_MNAME', models.CharField(blank=True, max_length=50, null=True)),
                ('RES_NICKNAME', models.CharField(blank=True, max_length=50, null=True)),
                ('RES_DOB', models.DateField()),
                ('RES_AGE', models.IntegerField(blank=True, null=True)),
                ('RES_SEX', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('RES_GENDER', models.CharField(blank=True, max_length=10, null=True)),
                ('RELIG_ID', models.IntegerField()),
                ('RES_CIVIL_STATUS', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated', 'Separated')], max_length=20)),
                ('RES_WEIGHT', models.CharField(max_length=10)),
                ('RES_EYE_COLOR', models.CharField(max_length=20)),
                ('RES_BLOOD_TYPE', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('ORG_ID', models.IntegerField(blank=True, null=True)),
                ('ADD_ID', models.IntegerField()),
                ('RES_ISOWNER', models.CharField(choices=[('Owner', 'Owner'), ('Not Owner', 'Not Owner')], max_length=15)),
                ('RES_ISACTIVE', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10)),
                ('EDUC_ID', models.IntegerField()),
                ('USER_ID', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('RES_LNAME', 'RES_FNAME', 'RES_MNAME')},
            },
        ),
    ]
